version: '3.7'
services:
  frontend:
    container_name: "frontend"
    build: 
      context: ./frontend
    stop_signal: SIGTERM
    ports:
      - "80:80"
    networks:
      - good_network
    depends_on:
      - backend

  backend:
    container_name: "backend"
    build:
      context: ./backend
    stop_signal: SIGTERM
    ports:
      - "8000:8000"
    networks:
      - good_network
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: postgres:16.0
    environment:
      POSTGRES_DB: "taskevin_sugar"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "joDcjToeAX"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d taskevin_sugar -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - good_network

networks:
  good_network:

volumes:
  postgres_data: